# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asyVarAUC_C <- function(tt, D_hat, mu_hat, Score, Hess_inv, Der_D1_hat, Der_D2_hat) {
    .Call('_bcROCcurve_asyVarAUC_C', PACKAGE = 'bcROCcurve', tt, D_hat, mu_hat, Score, Hess_inv, Der_D1_hat, Der_D2_hat)
}

aucFull_C <- function(tt, dd) {
    .Call('_bcROCcurve_aucFull_C', PACKAGE = 'bcROCcurve', tt, dd)
}

aucMAR_C <- function(tt, dd, vv, rho, pi) {
    .Call('_bcROCcurve_aucMAR_C', PACKAGE = 'bcROCcurve', tt, dd, vv, rho, pi)
}

aucFI_C <- function(tt, rho) {
    .Call('_bcROCcurve_aucFI_C', PACKAGE = 'bcROCcurve', tt, rho)
}

aucMSI_C <- function(tt, dd, vv, rho) {
    .Call('_bcROCcurve_aucMSI_C', PACKAGE = 'bcROCcurve', tt, dd, vv, rho)
}

aucIPW_C <- function(tt, dd, vv, pi) {
    .Call('_bcROCcurve_aucIPW_C', PACKAGE = 'bcROCcurve', tt, dd, vv, pi)
}

aucDR_C <- function(tt, dd, vv, rho, pi) {
    .Call('_bcROCcurve_aucDR_C', PACKAGE = 'bcROCcurve', tt, dd, vv, rho, pi)
}

